        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:49:53 2015
        MODULE PITCHCNTRL__genmod
          INTERFACE 
            SUBROUTINE PITCHCNTRL(BLPITCH,ELECPWR,HSS_SPD,GBRATIO,      &
     &TWRACCEL,NUMBL,ZTIME,DT,DIRROOT,BLPITCHCOM)
              INTEGER(KIND=4), INTENT(IN) :: NUMBL
              REAL(KIND=4), INTENT(IN) :: BLPITCH(NUMBL)
              REAL(KIND=4), INTENT(IN) :: ELECPWR
              REAL(KIND=4), INTENT(IN) :: HSS_SPD
              REAL(KIND=4), INTENT(IN) :: GBRATIO
              REAL(KIND=4), INTENT(IN) :: TWRACCEL
              REAL(KIND=4), INTENT(IN) :: ZTIME
              REAL(KIND=4), INTENT(IN) :: DT
              CHARACTER(LEN=1024), INTENT(IN) :: DIRROOT
              REAL(KIND=4), INTENT(OUT) :: BLPITCHCOM(NUMBL)
            END SUBROUTINE PITCHCNTRL
          END INTERFACE 
        END MODULE PITCHCNTRL__genmod
