        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:50:01 2015
        MODULE SET_FAST_PARAMS__genmod
          INTERFACE 
            SUBROUTINE SET_FAST_PARAMS
            END SUBROUTINE SET_FAST_PARAMS
          END INTERFACE 
        END MODULE SET_FAST_PARAMS__genmod
