        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:50:00 2015
        MODULE SETVERSION__genmod
          INTERFACE 
            SUBROUTINE SETVERSION
            END SUBROUTINE SETVERSION
          END INTERFACE 
        END MODULE SETVERSION__genmod
