        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:50:01 2015
        MODULE TFINAERO__genmod
          INTERFACE 
            SUBROUTINE TFINAERO(TFINCPXI,TFINCPYI,TFINCPZI,TFINCPVX,    &
     &TFINCPVY,TFINCPVZ)
              REAL(KIND=4), INTENT(IN) :: TFINCPXI
              REAL(KIND=4), INTENT(IN) :: TFINCPYI
              REAL(KIND=4), INTENT(IN) :: TFINCPZI
              REAL(KIND=4), INTENT(IN) :: TFINCPVX
              REAL(KIND=4), INTENT(IN) :: TFINCPVY
              REAL(KIND=4), INTENT(IN) :: TFINCPVZ
            END SUBROUTINE TFINAERO
          END INTERFACE 
        END MODULE TFINAERO__genmod
