        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:49:53 2015
        MODULE USERYAWCONT__genmod
          INTERFACE 
            SUBROUTINE USERYAWCONT(YAWPOS,YAWRATE,WINDDIR,YAWERROR,NUMBL&
     &,ZTIME,DT,DIRROOT,YAWPOSCOM,YAWRATECOM)
              INTEGER(KIND=4), INTENT(IN) :: NUMBL
              REAL(KIND=4), INTENT(IN) :: YAWPOS
              REAL(KIND=4), INTENT(IN) :: YAWRATE
              REAL(KIND=4), INTENT(IN) :: WINDDIR
              REAL(KIND=4), INTENT(IN) :: YAWERROR
              REAL(KIND=4), INTENT(IN) :: ZTIME
              REAL(KIND=4), INTENT(IN) :: DT
              CHARACTER(LEN=1024), INTENT(IN) :: DIRROOT
              REAL(KIND=4), INTENT(OUT) :: YAWPOSCOM
              REAL(KIND=4), INTENT(OUT) :: YAWRATECOM
            END SUBROUTINE USERYAWCONT
          END INTERFACE 
        END MODULE USERYAWCONT__genmod
