        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:35:18 2015
        MODULE USERRFRL__genmod
          INTERFACE 
            SUBROUTINE USERRFRL(RFRLDEF,RFRLRATE,ZTIME,DIRROOT,RFRLMOM)
              REAL(KIND=4), INTENT(IN) :: RFRLDEF
              REAL(KIND=4), INTENT(IN) :: RFRLRATE
              REAL(KIND=4), INTENT(IN) :: ZTIME
              CHARACTER(LEN=1024), INTENT(IN) :: DIRROOT
              REAL(KIND=4), INTENT(OUT) :: RFRLMOM
            END SUBROUTINE USERRFRL
          END INTERFACE 
        END MODULE USERRFRL__genmod
