        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:35:18 2015
        MODULE USERPTFMLD__genmod
          INTERFACE 
            SUBROUTINE USERPTFMLD(X,XD,ZTIME,DIRROOT,PTFMAM,PTFMFT)
              REAL(KIND=4), INTENT(IN) :: X(6)
              REAL(KIND=4), INTENT(IN) :: XD(6)
              REAL(KIND=4), INTENT(IN) :: ZTIME
              CHARACTER(LEN=1024), INTENT(IN) :: DIRROOT
              REAL(KIND=4), INTENT(OUT) :: PTFMAM(6,6)
              REAL(KIND=4), INTENT(OUT) :: PTFMFT(6)
            END SUBROUTINE USERPTFMLD
          END INTERFACE 
        END MODULE USERPTFMLD__genmod
