        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:35:18 2015
        MODULE USERTEET__genmod
          INTERFACE 
            SUBROUTINE USERTEET(TEETDEF,TEETRATE,ZTIME,DIRROOT,TEETMOM)
              REAL(KIND=4), INTENT(IN) :: TEETDEF
              REAL(KIND=4), INTENT(IN) :: TEETRATE
              REAL(KIND=4), INTENT(IN) :: ZTIME
              CHARACTER(LEN=1024), INTENT(IN) :: DIRROOT
              REAL(KIND=4), INTENT(OUT) :: TEETMOM
            END SUBROUTINE USERTEET
          END INTERFACE 
        END MODULE USERTEET__genmod
