        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:35:12 2015
        MODULE USERTWRLD__genmod
          INTERFACE 
            SUBROUTINE USERTWRLD(JNODE,X,XD,ZTIME,DIRROOT,TWRAM,TWRFT)
              INTEGER(KIND=4), INTENT(IN) :: JNODE
              REAL(KIND=4), INTENT(IN) :: X(6)
              REAL(KIND=4), INTENT(IN) :: XD(6)
              REAL(KIND=4), INTENT(IN) :: ZTIME
              CHARACTER(LEN=1024), INTENT(IN) :: DIRROOT
              REAL(KIND=4), INTENT(OUT) :: TWRAM(6,6)
              REAL(KIND=4), INTENT(OUT) :: TWRFT(6)
            END SUBROUTINE USERTWRLD
          END INTERFACE 
        END MODULE USERTWRLD__genmod
