        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:49:53 2015
        MODULE USERHSSBR__genmod
          INTERFACE 
            SUBROUTINE USERHSSBR(GENTRQ,ELECPWR,HSS_SPD,GBRATIO,NUMBL,  &
     &ZTIME,DT,DIRROOT,HSSBRFRAC)
              INTEGER(KIND=4), INTENT(IN) :: NUMBL
              REAL(KIND=4), INTENT(IN) :: GENTRQ
              REAL(KIND=4), INTENT(IN) :: ELECPWR
              REAL(KIND=4), INTENT(IN) :: HSS_SPD
              REAL(KIND=4), INTENT(IN) :: GBRATIO
              REAL(KIND=4), INTENT(IN) :: ZTIME
              REAL(KIND=4), INTENT(IN) :: DT
              CHARACTER(LEN=1024), INTENT(IN) :: DIRROOT
              REAL(KIND=4), INTENT(OUT) :: HSSBRFRAC
            END SUBROUTINE USERHSSBR
          END INTERFACE 
        END MODULE USERHSSBR__genmod
