        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:35:18 2015
        MODULE USERTFIN__genmod
          INTERFACE 
            SUBROUTINE USERTFIN(TFRLDEF,TFRLRATE,ZTIME,DIRROOT,TFINCPXI,&
     &TFINCPYI,TFINCPZI,TFINCPVX,TFINCPVY,TFINCPVZ,TFINAOA,TFINQ,TFINCL,&
     &TFINCD,TFINKFX,TFINKFY)
              REAL(KIND=4), INTENT(IN) :: TFRLDEF
              REAL(KIND=4), INTENT(IN) :: TFRLRATE
              REAL(KIND=4), INTENT(IN) :: ZTIME
              CHARACTER(LEN=1024), INTENT(IN) :: DIRROOT
              REAL(KIND=4), INTENT(IN) :: TFINCPXI
              REAL(KIND=4), INTENT(IN) :: TFINCPYI
              REAL(KIND=4), INTENT(IN) :: TFINCPZI
              REAL(KIND=4), INTENT(IN) :: TFINCPVX
              REAL(KIND=4), INTENT(IN) :: TFINCPVY
              REAL(KIND=4), INTENT(IN) :: TFINCPVZ
              REAL(KIND=4), INTENT(OUT) :: TFINAOA
              REAL(KIND=4), INTENT(OUT) :: TFINQ
              REAL(KIND=4), INTENT(OUT) :: TFINCL
              REAL(KIND=4), INTENT(OUT) :: TFINCD
              REAL(KIND=4), INTENT(OUT) :: TFINKFX
              REAL(KIND=4), INTENT(OUT) :: TFINKFY
            END SUBROUTINE USERTFIN
          END INTERFACE 
        END MODULE USERTFIN__genmod
