        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 02:35:18 2015
        MODULE USERTFRL__genmod
          INTERFACE 
            SUBROUTINE USERTFRL(TFRLDEF,TFRLRATE,ZTIME,DIRROOT,TFRLMOM)
              REAL(KIND=4), INTENT(IN) :: TFRLDEF
              REAL(KIND=4), INTENT(IN) :: TFRLRATE
              REAL(KIND=4), INTENT(IN) :: ZTIME
              CHARACTER(LEN=1024), INTENT(IN) :: DIRROOT
              REAL(KIND=4), INTENT(OUT) :: TFRLMOM
            END SUBROUTINE USERTFRL
          END INTERFACE 
        END MODULE USERTFRL__genmod
