        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 14 03:01:06 2015
        MODULE USERGEN__genmod
          INTERFACE 
            SUBROUTINE USERGEN(HSS_SPD,GBRATIO,NUMBL,ZTIME,DT,GENEFF,   &
     &DELGENTRQ,DIRROOT,GENTRQ,ELECPWR)
              REAL(KIND=4), INTENT(IN) :: HSS_SPD
              REAL(KIND=4), INTENT(IN) :: GBRATIO
              INTEGER(KIND=4), INTENT(IN) :: NUMBL
              REAL(KIND=4), INTENT(IN) :: ZTIME
              REAL(KIND=4), INTENT(IN) :: DT
              REAL(KIND=4), INTENT(IN) :: GENEFF
              REAL(KIND=4), INTENT(IN) :: DELGENTRQ
              CHARACTER(LEN=1024), INTENT(IN) :: DIRROOT
              REAL(KIND=4), INTENT(OUT) :: GENTRQ
              REAL(KIND=4), INTENT(OUT) :: ELECPWR
            END SUBROUTINE USERGEN
          END INTERFACE 
        END MODULE USERGEN__genmod
